import { Arrow, SiteFooter, SiteHeader } from "../components/SiteChrome";
import { team } from "../components/team";

export default function Home() {
  return <main>
    <SiteHeader />
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">UC IRVINE · DIGITAL LEARNING LAB</p><h1><span className="hero-product-name">My Story Detective</span><span className="hero-description">An AI-supported<br />literacy coach for<br />struggling readers.</span></h1><p className="hero-lede">Personalized support for every K–2 student, grounded in the science of reading—interactive, patient, and built to work at scale.</p></div><div className="hero-proof" aria-label="The challenge My Story Detective addresses"><p className="proof-label">THE READING GAP</p><div><strong>~40%</strong><span>of K–2 students struggle with foundational reading skills</span></div><div><strong>1-on-1</strong><span>tutoring works best—but districts cannot deliver it at scale</span></div><p className="proof-note">My Story Detective brings individualized support into existing literacy time.</p></div></section>

    <section className="challenge home-about"><p className="section-kicker">ABOUT MY STORY DETECTIVE</p><div><h2>Responsive literacy support for more young readers.</h2><p>My Story Detective is a web-based, AI-supported literacy experience that helps K–2 students build language, comprehension, and word-reading skills through illustrated stories. It extends skilled, responsive support while keeping teachers at the center.</p><a className="primary-cta" href="/about">Learn about the project <Arrow /></a></div></section>

    <section className="platform"><div className="section-head"><p className="section-kicker">THE PLATFORM</p><h2>A connected reading experience.</h2><p>An AI literacy coach that works like a skilled tutor—interactively, patiently, and at scale.</p></div><div className="platform-home-overview"><div><p><span className="platform-tagline">Stories become conversations.</span> My Story Detective brings illustrated stories, guided conversation, and word-reading practice into one connected experience. Children build meaning as they talk about stories and practice the skills that help them read independently. Designed for school and accessible at home, it extends individualized literacy support wherever children read.</p><a className="primary-cta" href="/platform">Explore the platform <Arrow /></a></div><div className="platform-home-visual-pair"><img src="/platform/story-preview.png" alt="Illustrated sailboat storybook page used for interactive co-reading" /><img src="/platform/dialogue-preview.jpg" alt="Conversation interface showing comprehension monitoring, inferencing, and language-building prompts" /></div></div></section>

    <section className="research"><div className="research-copy"><p className="section-kicker">RESEARCH FOUNDATION</p><h2>Built on a decade of UCI research.</h2><p>My Story Detective builds on two UCI research foundations: early-literacy research led by Professor Young-Suk Kim and the UCI Digital Learning Lab’s Converse to Learn project, which explores AI-supported dialogic learning.</p><div className="research-home-foundations"><article><span>EARLY LITERACY RESEARCH</span><h3>Language, comprehension, and word reading</h3><p>Professor Young-Suk Kim’s research and the Story Detective and COMPASS interventions inform the project’s focus on the connected skills children use as they become readers.</p></article><article><span>CONVERSE TO LEARN</span><h3>Dialogic reading with conversational agents</h3><p>The UCI Digital Learning Lab’s Converse to Learn project explores how conversational agents can support children’s engagement, comprehension, and vocabulary during story-based learning.</p></article></div><div className="cta-group"><a className="primary-cta" href="/research">Explore the research <Arrow /></a><a className="secondary-cta" href="https://drive.google.com/file/d/1ctN0dnZ_LHgHw8Fqo_cQmauMs7ADeHUx/view" target="_blank" rel="noreferrer">View Grant Proposal <Arrow /></a></div></div><div className="research-support"><p>PROJECT FUNDING &amp; RELATED SUPPORT</p><div className="agency-row"><span><b>U.S. Department of Education</b><small>Supports My Story Detective</small></span><span><b>National Science Foundation</b><small>Supports related storybook development</small></span></div></div></section>

    <section className="people people-teaser"><div className="section-head"><p className="section-kicker">THE TEAM</p><h2>Research team behind the platform.</h2><p>Deep expertise in AI, early reading development, multilingual learning, and classroom practice.</p></div><div className="people-teaser-content"><div className="team-portrait-strip" aria-hidden="true">{team.map(person => <span className="team-portrait" key={person.name}><img src={person.image} alt="" /></span>)}</div><div><p>Meet the researchers and educators guiding My Story Detective.</p><a className="primary-cta" href="/people">Meet the team <Arrow /></a></div></div></section>

    <section className="contact contact-teaser"><div><p className="section-kicker">CONTACT US</p><h2>Bring individualized literacy support to your school.</h2></div><div><p>Interested in becoming a research and development partner? Learn how to start a conversation with the My Story Detective team.</p><a className="contact-button" href="/contact">Contact us <Arrow /></a></div></section>
    <SiteFooter />
  </main>;
}
